## way below not recommended but it can be useful in case we need to install REALLY LOT of packages
#- name: install docker* app.
#  shell:
#    cmd: 'apt-get install -y docker-compose docker.io'
#    warn: false

## special ansible module for manage packages is preferred to use
- name: install docker-compose
  apt:
    name: docker-compose
    state: present
#   update_cache: yes
#   option above not needed because we have done it in initial configuration and no new repos were added

- name: install docker.io
  apt:
    name: docker.io
    state: present
#   update_cache: yes
#   option above not needed because we have done it in initial configuration and no new repos were added
