- name: Test PING
  hosts: ttaskL
  become: yes
  tasks:
    - name: ping
      ping:

- name: Initial VM configuration
  hosts: ttaskL
  become: yes
  roles:
    - initial_configuration

- name: Install docker packages
  hosts: ttaskL
  become: yes
  roles:
    - docker_node_setup

- name: Provision prometheus container
  hosts: ttaskL
  become: yes
  roles:
    - docker_provision_prometheus

- name: Provision grafana container
  hosts: ttaskL
  become: yes
  roles:
    - docker_provision_grafana

- name: Install node_exporter for prometheus
  hosts: ttaskL
  become: yes
  roles:
    - install_node_exporter
