global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  - "alert.rules"

scrape_configs:
    scrape_interval: 10s
  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']
