global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  - "alert.rules"

scrape_configs:
  - job_name: 'node'
    metrics_path: /metrics
    scrape_interval: 10s
    static_configs:
      - targets: ['host.docker.internal:9100']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['127.0.0.1:9090']
