version: '3.7'

volumes:
    grafana: {}
    grafana_data: {}
    grafana_logs: {}

services:

  grafana:
    image: grafana/grafana:9.3.2
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana_data:/var/lib/grafana
      - ./grafana/:/etc/grafana/
      - ./grafana_logs/:/var/log/grafana/
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/var/lib/grafana/dashboards/1860.json
      - GF_SECURITY_ADMIN_PASSWORD=123qwe
      - GF_USERS_ALLOW_SIGN_UP=false
      - DS_PROMETHEUS=Prometheus
#    env_file:
#      - ./config.monitoring
    restart: unless-stopped

    networks:
      - default
      - prome_graf

networks:
  prome_graf:
    external:
      name:  prome_graf_net
