- name: update package manager cache
  apt:
    update_cache: yes

- name: install docker-compose
  apt:
    name: docker-compose
    state: present

- name: install docker.io
  apt:
    name: docker.io
    state: present

- name: add Vagrant user to the docker group
  ansible.builtin.user:
    name: vagrant
    groups: docker
    append: yes
